### ISSUE TITLE
Issue 3 : Error about an unknown value about accmin.

### ISSUE THREAD

**Issue by dobodu** [dobodu/ICM20948_DMP_Micropython#2]
in your last modified file, Row 832, I have an error about an unknown value about accmin. Other values are magmin

_Originally posted by @JeromeRaymond in https://github.com/dobodu/ICM20948_DMP_Micropython/issues/1#issuecomment-2537307815_

**Comment by dobodu** [comment]
Strange,

For me icm20948_test.py is working fine.
I reuploaded the library jsut in case....

**Comment by dobodu** [comment]
MPY: soft reboot
Shall we use DMP (y/n) ? n
DBG:	 ICM20948 :	 DEVICE FOUND AT ADDRESS 0x68
DBG:	 ICM20948 :	 CHIP ID NUMBER IS 0xea
DBG:	 ICM20948 :	 AK09916 Magnetometer Chip Found... 
DBG:	 ICM20948 :	 AK09916 Magnetometer Chip Reseted... 
DBG:	 ICM20948 :	 Gyroscope calibration done (1.067073, 0.09146341, 0.2134146)

Accel: 00.03 00.04 01.03
Gyro:  00.09 00.21 00.21
Mag:   -13.20 05.70 -93.00
HPT:   -13.209  74.885  62.181

**Comment by JeromeRaymond** [comment]
In my script, if I call imu.acc_cal()
the result is:
>>> %Run -c $EDITOR_CONTENT

MPY: soft reboot
DBG:	 ICM20948 :	 DEVICE FOUND AT ADDRESS 0x69
DBG:	 ICM20948 :	 CHIP ID NUMBER IS 0xea
DBG:	 ICM20948 :	 AK09916 Magnetometer Chip Found... 
DBG:	 ICM20948 :	 AK09916 Magnetometer Chip Reseted... 
DBG:	 ICM20948 :	 Gyroscope calibration done (-0.5487805, 0.7317073, 0.0)
Traceback (most recent call last):
  File "<stdin>", line 20, in <module>
  File "icm20948.py", line 832, in acc_cal
NameError: name 'accmin' isn't defined

In Row Acc_cal, variables are about magmax and magmin but in row 832, you call accmin and accmax.

**Comment by dobodu** [comment]
I'll give a look this evening,
Ca you provide the main script you are using.
I've been focusing on the bug related to compass (and in fact general DMP outputs). Let's focus on other small bugs.

**Comment by dobodu** [comment]
Strange...

When running the icm20948_test.py

```
if not imu.dmp_ready :
    
    imu.gyro_cal()

    while True:
        a = imu.acc()
        g = imu.gyro()
        m = imu.mag()   # Read directly to the slave
        imu.Q_update_full(m, a, g)
        heading = imu.heading
        pitch = imu.pitch
        roll = imu.roll

        print(f"""
Accel: {a[0]:05.2f} {a[1]:05.2f} {a[2]:05.2f}
Gyro:  {g[0]:05.2f} {g[1]:05.2f} {g[2]:05.2f}
Mag:   {m[0]:05.2f} {m[1]:05.2f} {m[2]:05.2f}
HPT:   {heading:7.3f} {pitch:7.3f} {roll:7.3f}
""")
```

I have an output without error... (as in msg 2)

Shall we use DMP (y/n) ? n
DBG:	 ICM20948 :	  DEVICE FOUND AT ADDRESS 0x68
DBG:	 ICM20948 :	  CHIP ID NUMBER IS 0xea
DBG:	 ICM20948 :	  AK09916 Magnetometer Chip Found... 
DBG:	 ICM20948 :	  AK09916 Magnetometer Chip Reseted... 
DBG:	 ICM20948 :	  Gyroscope calibration done (0.7621951, -0.2439024, 0.152439)

Accel: 00.03 00.05 01.03
Gyro:  00.03 -0.18 -0.03
Mag:   -17.40 01.20 -104.70
HPT:    99.510  -1.093  23.523

Can you provide the script you use and maybe the micropython version you are using ?

**Comment by dobodu** [comment]
All right... I found it, just a copy/paste error without correction.

Updated in repository

**Comment by dobodu** [comment]
Repository updated
